### ISSUE TITLE
Logging Issue

### ISSUE THREAD

**Issue by lorenzohanssens** [Fuwn/soyuz#1] opened 2022-02-03 13:19 UTC
The log system filled my D drive till the very last bit.

![Screenshot_3](https://user-images.githubusercontent.com/36443552/152350353-ca1aaed9-5dda-4035-b92b-67befa4f4b00.png)

Opening it with Lunar closed for example, will make the file 214MB even after closing it 10s later. (Fully closed, tray as well)

![Screenshot_4](https://user-images.githubusercontent.com/36443552/152353466-d64bf43d-1021-4e97-8f17-155cc1962f31.png)

Seems to fully spam the log if the required processes (RPC requests) aren't found.

**Comment by Fuwn** [comment] 2022-02-03 20:21
Very bizarre. How were you able to open Soyuz while Lunar Client was closed? There's a check in place to make sure Soyuz will close itself if Lunar Client isn't open.

**Comment by Fuwn** [comment] 2022-02-03 20:26
I figure you meant opening Soyuz **then** closing Lunar Client? In which case yeah, I get the same behavior.

**Comment by lorenzohanssens** [comment] 2022-02-03 20:59
Nope I'm able to open Soyuz without Lunar Client being open (launcher included too).

**Comment by Fuwn** [comment] 2022-02-03 21:27
> Nope I'm able to open Soyuz without Lunar Client being open (launcher included too).

That is very odd, are you using the latest version compiled yourself? The executables within the releases are not always up to date.

**Comment by Fuwn** [comment] 2022-02-03 21:40
@LorenzoHanssens, release [1.1.2](https://github.com/Fuwn/soyuz/releases/tag/1.1.2) is fully up-to-date if you'd like to see if it fixes your problem.

**Comment by lorenzohanssens** [comment] 2022-02-04 06:33
It does cause less spam and a lower filesize.
However, when closing the app (not in tray either) and trying to delete the log, I found out 
![image](https://user-images.githubusercontent.com/36443552/152482963-d7d35b6d-3f49-4fa4-b005-5207b6c495e3.png)
![image](https://user-images.githubusercontent.com/36443552/152483022-78659cb5-0f69-4540-a5a4-0b81bc09a707.png)
the process just stops working (and locks the log file)

If you're wondering what the log file looks like, 
[soyuz.log](https://github.com/Fuwn/soyuz/files/8000657/soyuz.log)


All in all, thank you for getting on this issue so quickly!

**Comment by Fuwn** [comment] 2022-02-06 01:43
Sorry about the delay, I wanted to address this issue yesterday but it totally slipped my mind.

I was unable to reproduce this error, can you detail exactly how you arrived to that point?

**Comment by lorenzohanssens** [comment] 2022-02-09 12:20
Sorry for taking so long to reply myself.

To reproduce this, you need to have Lunar open.
Then, in the tray just right click and quit Soyuz.
The app itself will say "requesting exit" and then stop responding (at least on my system, Windows 11).

As long as it isn't responding I can't delete the log file however that's not that important.

![Screenshot_2](https://user-images.githubusercontent.com/36443552/153199660-a9353cb0-0c00-4c24-af29-133118697702.png)

**Comment by Fuwn** [comment] 2022-02-10 05:26
If all is correct, https://github.com/Fuwn/soyuz/commit/9f5f2567276426ae73e96beff028d3c2f33c53db should fix that problem.

**Comment by Fuwn** [comment] 2022-03-11 12:21
Any updates, @LorenzoHanssens?

**Comment by lorenzohanssens** [comment] 2022-03-11 12:57
> Any updates, @LorenzoHanssens?

sorry I'm currently out of the country, can't confirm this yet

**Closed as completed** 2023-01-19 22:45 UTC
Labels: bug
